---
title: "More details"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{more_details}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(xrayr)
library(ggplot2)
```

```{r}
head(xray_spec, 5)
```
```{r}
ggplot(
  data = xray_spec,
  mapping = aes(
    x = energy,
    y = flux_model,
    xwidth = err_energy,
    color = telescope
  )
) +
  geom_xray_stepcount() +
  geom_xray_pointrange(aes(y = flux_obs, ywidth = err_obs), 
                       upper_nsigma = 3, # default 2 
                       min_y = 1e-2 # default NULL -> automatic
                       ) +
  scale_x_log10(breaks = c(0.3, 1, 4, 7, 12, 20)) + 
  scale_y_log10() +
  annotation_logticks() +
  scale_color_brewer(palette = 'Set1') +
  xlab('Energy, keV') +
  ylab('cts/s/keV') +
  theme_xray_plot()
```
```{r}
ggplot(xray_spec, aes(color = telescope)) +
  geom_xray_ratio(aes(
    x = energy,
    xwidth = err_energy,
    obs = flux_obs,
    obs_err = err_obs,
    model = flux_model
  )) +
  geom_hline(yintercept = 1) +
  scale_x_log10(breaks = c(0.3, 1, 4, 7, 12, 20)) +
  annotation_logticks(sides = 'b') +
  xlab('Energy, keV') +
  ylab('obs/model') +
  scale_color_brewer(palette = 'Set1') +
  theme_xray_plot()
```

